# Uncomment the variable below to enable swap partition creation. Note that the
# swap partition will only be generated during the initial boot, before the
# disk partition layout is finalized.
#SWAP_SIZE=2048M
