#!/bin/sh
### BEGIN INIT INFO
# Provides: firstboot
# Required-Start: mountall-bootclean
# Required-Stop: 
# Default-Start: 2 3 4 5 S
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting firstboot" &&
            /sbin/firstboot-resizefs.sh && log_end_msg $?
        ;;
    stop)
        ;;
    restart)
        ;;
    force-reload)
        ;;
    *)
        echo "Usage: $0 start" >&2
        exit 3
        ;;
esac
