#!/bin/sh

set -e

RCLOCAL="/etc/rc.local"
FIRSTBOOT_SCRIPT="/sbin/firstboot-resizefs.sh"

sed -i '/exit 0/d' ${RCLOCAL}
sed -i '/${FIRSTBOOT_SCRIPT}/d' ${RCLOCAL}

cat>>${RCLOCAL}<<__EOF
test -f ${FIRSTBOOT_SCRIPT} && ${FIRSTBOOT_SCRIPT}
exit 0
__EOF
